import React from 'react';
import { motion } from 'motion/react';
import { 
  X, 
  DollarSign, 
  TrendingUp, 
  GraduationCap, 
  Scale, 
  CheckCircle2
} from 'lucide-react';

interface CareerFitDetailModalProps {
  type: 'salary' | 'demand' | 'learning' | 'balance' | null;
  roleTitle: string;
  onClose: () => void;
}

export const CareerFitDetailModal: React.FC<CareerFitDetailModalProps> = ({
  type,
  roleTitle,
  onClose
}) => {
  if (!type) return null;

  // HerNext does not publish salary bands, hiring-market statistics or employer
  // research, and the backend has no endpoint that returns them. Rather than
  // ship invented figures, each panel states what is unavailable and points at
  // the real data HerNext does calculate for the participant.
  const dataMap = {
    salary: {
      title: 'Compensation Data',
      rating: 'Not available',
      icon: DollarSign,
      color: 'text-gray-600',
      bgColor: 'bg-gray-50 border-gray-200',
      description:
        'HerNext does not collect or publish salary data, so no pay range is shown here. Adding a figure would mean inventing one.',
      bullets: [
        'Your career match and match score come from the HerNext backend',
        'Match scores reflect skill alignment only, not pay',
        'Research pay yourself using the target role title shown above'
      ]
    },
    demand: {
      title: 'Job Market Data',
      rating: 'Not available',
      icon: TrendingUp,
      color: 'text-gray-600',
      bgColor: 'bg-gray-50 border-gray-200',
      description:
        'HerNext has no hiring-market or job-postings data source, so no demand figures are shown here. Any growth rate or opening count here would be fabricated.',
      bullets: [
        'HerNext ranks careers from the approved catalogue and your skills',
        'Your ranked matches are on Career Insights',
        'Skill gaps for your target career are on My Skills'
      ]
    },
    learning: {
      title: 'Skill Gaps For This Career',
      rating: 'Not available here',
      icon: GraduationCap,
      color: 'text-gray-600',
      bgColor: 'bg-gray-50 border-gray-200',
      description:
        'HerNext does not estimate how long a transition will take. It does calculate the specific skills you already have and the ones you still need for this career.',
      bullets: [
        'Open My Skills to see your real gap list for this career',
        'Roadmap tasks are generated by the backend from that gap list',
        'No study-time or experience-match estimate is invented here'
      ]
    },
    balance: {
      title: 'Working Conditions Data',
      rating: 'Not available',
      icon: Scale,
      color: 'text-gray-600',
      bgColor: 'bg-gray-50 border-gray-200',
      description:
        'HerNext has no employer or workplace data, so remote availability, hours and benefits are not reported. None of these values could be verified.',
      bullets: [
        'Ask the employer directly about hours, remote policy and benefits',
        'HerNext focuses on your skills, readiness and career matches',
        'Nothing about a specific employer is stored on your account'
      ]
    }
  };

  const details = dataMap[type];
  const Icon = details.icon;

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
      className="fixed inset-0 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 overflow-y-auto"
    >
      <motion.div 
        initial={{ scale: 0.95, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.95, opacity: 0, y: 20 }}
        onClick={(e) => e.stopPropagation()}
        className="bg-white rounded-3xl max-w-md w-full shadow-2xl border border-purple-100 overflow-hidden my-6 text-gray-800"
      >
        <div className="bg-[#261338] text-white p-5 relative">
          <button 
            onClick={onClose}
            className="absolute top-5 right-5 text-white/70 hover:text-white bg-white/10 p-1.5 rounded-full cursor-pointer"
          >
            <X size={18} />
          </button>
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-xl bg-purple-500/20 text-[#F05A7E] flex items-center justify-center">
              <Icon size={18} />
            </div>
            <div>
              <span className="text-[10px] text-purple-200/70 font-semibold uppercase tracking-wider block">Career Fit Inspector</span>
              <h3 className="text-base font-bold text-white">{details.title}</h3>
            </div>
          </div>
          <span className="text-xs text-purple-200/80">
            Path: <strong>{roleTitle}</strong>
          </span>
        </div>

        <div className="p-5 space-y-4 text-xs">
          <div className={`p-4 rounded-2xl border ${details.bgColor} space-y-1`}>
            <span className="text-[10px] font-bold uppercase tracking-wider block text-gray-500">HerNext Data Availability</span>
            <span className={`text-lg font-black ${details.color}`}>{details.rating}</span>
            <p className="text-gray-700 leading-relaxed mt-1">{details.description}</p>
          </div>

          <div>
            <h4 className="font-bold text-[#2D1B4E] uppercase tracking-wider text-[10px] text-gray-500 mb-2">
              What HerNext Can Show You Instead
            </h4>
            <div className="space-y-2">
              {details.bullets.map((b, i) => (
                <div key={i} className="flex items-start gap-2 text-gray-700">
                  <CheckCircle2 size={14} className="text-emerald-500 shrink-0 mt-0.5" />
                  <span>{b}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="p-4 bg-gray-50 border-t border-gray-100 text-right">
          <button 
            onClick={onClose}
            className="px-5 py-2 bg-[#2D1B4E] hover:bg-[#431F69] text-white text-xs font-bold rounded-xl transition-all cursor-pointer"
          >
            Got It
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
};

export default CareerFitDetailModal;
